# -*- coding: utf-8 -*-
"""image detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S16BNbXSA6r3oRqzQ4nQLEiuze_LJO5c
"""

!pip install pillow
!pip install lxml
!pip install jupyter
!pip install matplotlib

! git clone https://github.com/thtrieu/darkflow.git

!pwd

pwd

!ls

cd darkflow/

!ls

!python setup.py build_ext --inplace

!pip install Cython

ls

mkdir bin

cd  bin

ls

cd ..

ls

cd  test/

ls

cd ..

cd  bin

ls

cd ..

ls

cd ..

ls

cp yolov2.weights darkflow/bin/

cp videoplayback.mp4 darkflow/

cd darkflow/

ls

ls

!python flow --model cfg/yolo.cfg --load bin/yolov2.weights  --demo videoplayback.mp4 --gpu 1.0 --saveVideo

ls

ls

